os: linux
dist: xenial
language: python
python:
- 3.7
- 3.8
- nightly

matrix:
  include:
  - name: coverage
    language: python
    python: 3.7
    before_script:
    - CARGO_TARGET_DIR="${HOME}/.cargo/target" cargo install grcov
    script:
    - VERBOSE=1 python3 c.py test --mode coverage
    - export CARGO_INCREMENTAL=0
    - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
    - cargo test --verbose
    after_success:
    - zip -0 ccov.zip `find . \( -name "porus*.gc*" \) -print`;
    - grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
    - bash <(curl -s https://codecov.io/bash) -f lcov.info;
  - os: osx
    language: generic
    python: 3.7
    before_install:
    - curl -Lo python.pkg https://www.python.org/ftp/python/3.7.3/python-3.7.3-macosx10.6.pkg
    - sudo installer -pkg python.pkg -target /
    - /Applications/Python\ 3.7/Install\ Certificates.command
  allow_failures:
  - python: nightly
  - name: coverage
env:
  global:
  - PATH=${PATH}:${HOME}/.cargo/bin
  matrix:
  - TRAVIS_RUST_VERSION=nightly
install:
- curl -sSf https://sh.rustup.rs/ | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
- rustup component add rustc-dev
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rustup target add x86_64-unknown-linux-gnu; fi
- pip3 install -r requirements.txt
script:
- VERBOSE=1 python3 c.py test
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then VERBOSE=1 python3 c.py test --mode release; fi
cache:
  pip: true
  directories:
  - $HOME/.cargo
  - $HOME/.cache/wronganswer/data
  - $TRAVIS_BUILD_DIR/target
