name: Lint

on: [push]

jobs:
  rustfmt:
    name: rustfmt

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
        default: true
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - run: find solutions -name '*.rs' | xargs -I {} rustfmt --edition 2018 --check {}

    - run: find examples -name '*.rs' | xargs -I {} rustfmt --edition 2018 --check {}

  clippy:
    name: clippy

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy, rustc-dev
        default: true
        override: true

    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-features

    - run: cd porus_macros && cargo clippy
