name: Test

on: [push]


jobs:
  porus-debug:
    name: test debug

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustc-dev
        default: true
        override: true

    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

  porus-release:
    name: test release

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustc-dev
        default: true
        override: true

    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --verbose
